# Generated by Django 4.2.9 on 2025-12-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_plus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usern8nprofile',
            name='onboarding_completed',
        ),
    ]
