# Generated by Django 4.2.9 on 2025-12-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_plus', '0002_remove_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='usern8nprofile',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='usern8nprofile',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
