# Generated by Django 4.2.9 on 2025-12-02 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts_plus', '0003_add_openai_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIKeyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, unique=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text="Disable key if it's revoked or invalid")),
                ('notes', models.TextField(blank=True, default='', help_text='Admin notes about this key')),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_openai_key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpenAI API Key',
                'verbose_name_plural': 'OpenAI API Keys Pool',
                'ordering': ['created_at'],
            },
        ),
    ]
