# Generated by Django 4.2.9 on 2025-12-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('magic_notifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('push', 'Push')], max_length=30)),
                ('gateway', models.CharField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('is_test', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='magic_notifier.notification')),
                ('recipient_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel'], name='magic_notif_channel_4a963a_idx'), models.Index(fields=['status'], name='magic_notif_status_aba8e0_idx'), models.Index(fields=['gateway'], name='magic_notif_gateway_853809_idx'), models.Index(fields=['provider'], name='magic_notif_provide_40f4d3_idx'), models.Index(fields=['created_at'], name='magic_notif_created_cfce7b_idx')],
            },
        ),
    ]
