# Generated by Django 4.2.9 on 2025-12-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmapsLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_id', models.CharField(blank=True, help_text='Input batch ID', max_length=255, null=True)),
                ('cid', models.CharField(blank=True, db_index=True, help_text='Google Maps CID', max_length=100, null=True)),
                ('data_id', models.CharField(blank=True, help_text='Google Maps data ID', max_length=100, null=True)),
                ('title', models.CharField(help_text='Business name', max_length=500)),
                ('link', models.URLField(blank=True, help_text='Google Maps link', max_length=2000, null=True)),
                ('category', models.CharField(blank=True, help_text='Business category', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Full address', null=True)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=50, null=True)),
                ('website', models.URLField(blank=True, help_text='Business website', max_length=2000, null=True)),
                ('plus_code', models.CharField(blank=True, help_text='Google Plus Code', max_length=100, null=True)),
                ('emails', models.TextField(blank=True, help_text='Email addresses (comma-separated or JSON)', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('timezone', models.CharField(blank=True, help_text='Timezone', max_length=100, null=True)),
                ('complete_address', models.JSONField(blank=True, help_text='Parsed address as JSON (borough, street, city, postal_code, state, country)', null=True)),
                ('open_hours', models.JSONField(blank=True, help_text='Opening hours as JSON', null=True)),
                ('popular_times', models.JSONField(blank=True, help_text='Popular times data as JSON', null=True)),
                ('review_count', models.IntegerField(default=0, help_text='Number of reviews')),
                ('review_rating', models.DecimalField(blank=True, decimal_places=1, help_text='Average rating', max_digits=3, null=True)),
                ('reviews_per_rating', models.JSONField(blank=True, help_text='Review distribution per rating as JSON', null=True)),
                ('reviews_link', models.URLField(blank=True, help_text='Link to reviews', max_length=2000, null=True)),
                ('user_reviews', models.JSONField(blank=True, help_text='User reviews as JSON', null=True)),
                ('user_reviews_extended', models.JSONField(blank=True, help_text='Extended user reviews as JSON', null=True)),
                ('thumbnail', models.URLField(blank=True, help_text='Thumbnail image URL', max_length=2000, null=True)),
                ('images', models.JSONField(blank=True, help_text='Images as JSON array', null=True)),
                ('status', models.CharField(blank=True, help_text='Business status', max_length=100, null=True)),
                ('descriptions', models.TextField(blank=True, help_text='Business descriptions', null=True)),
                ('price_range', models.CharField(blank=True, help_text='Price range indicator', max_length=50, null=True)),
                ('about', models.JSONField(blank=True, help_text='About section as JSON (accessibility, amenities, etc.)', null=True)),
                ('reservations', models.JSONField(blank=True, help_text='Reservation links as JSON', null=True)),
                ('order_online', models.JSONField(blank=True, help_text='Online ordering links as JSON', null=True)),
                ('menu', models.JSONField(blank=True, help_text='Menu link as JSON', null=True)),
                ('owner', models.JSONField(blank=True, help_text='Owner information as JSON (id, name, link)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Maps Lead',
                'verbose_name_plural': 'Google Maps Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='gmaps_leads_title_d5f172_idx'), models.Index(fields=['category'], name='gmaps_leads_categor_2542b8_idx'), models.Index(fields=['phone'], name='gmaps_leads_phone_e8a392_idx'), models.Index(fields=['review_rating'], name='gmaps_leads_review__11ae7b_idx')],
            },
        ),
    ]
