# Generated by Django 4.2.9 on 2025-12-09 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmaps_leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='External job ID from scraper API', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Job name/description', max_length=255)),
                ('keywords', models.JSONField(help_text='List of search keywords')),
                ('lang', models.CharField(default='en', help_text='Language code', max_length=10)),
                ('zoom', models.IntegerField(default=15, help_text='Map zoom level')),
                ('lat', models.CharField(blank=True, help_text='Latitude', max_length=50, null=True)),
                ('lon', models.CharField(blank=True, help_text='Longitude', max_length=50, null=True)),
                ('fast_mode', models.BooleanField(default=False, help_text='Enable fast mode')),
                ('radius', models.IntegerField(blank=True, help_text='Search radius', null=True)),
                ('depth', models.IntegerField(default=1, help_text='Search depth')),
                ('email', models.BooleanField(default=False, help_text='Extract emails')),
                ('max_time', models.IntegerField(default=3600, help_text='Maximum time in seconds')),
                ('proxies', models.JSONField(blank=True, help_text='List of proxies', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('leads_count', models.IntegerField(default=0, help_text='Number of leads found')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrape_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scrape Job',
                'verbose_name_plural': 'Scrape Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gmapslead',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='gmaps_leads.scrapejob'),
        ),
    ]
