# Generated by Django 4.2.9 on 2025-12-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0002_scrapejob_gmapslead_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='csv_file_path',
            field=models.CharField(blank=True, help_text='Path to downloaded CSV file', max_length=500, null=True),
        ),
    ]
