# Generated by Django 4.2.9 on 2025-12-09 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0003_scrapejob_csv_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number (digits only)', max_length=20)),
                ('chat_id', models.CharField(db_index=True, help_text='WhatsApp Chat ID (905XXXXXXXX@c.us)', max_length=50)),
                ('jid', models.CharField(db_index=True, help_text='WhatsApp JID (905XXXXXXXX@s.whatsapp.net)', max_length=50)),
                ('lid', models.CharField(blank=True, help_text='WhatsApp LID (reserved for future use)', max_length=100, null=True)),
                ('business_name', models.CharField(help_text='Business name from lead', max_length=500)),
                ('category', models.CharField(blank=True, help_text='Business category', max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this WhatsApp number has been verified')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this is a valid WhatsApp number')),
                ('last_checked', models.DateTimeField(blank=True, help_text='Last time the number was validated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contact', to='gmaps_leads.gmapslead')),
            ],
            options={
                'verbose_name': 'WhatsApp Contact',
                'verbose_name_plural': 'WhatsApp Contacts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number'], name='gmaps_leads_phone_n_6d06cb_idx'), models.Index(fields=['chat_id'], name='gmaps_leads_chat_id_019a90_idx'), models.Index(fields=['is_verified'], name='gmaps_leads_is_veri_5578ac_idx')],
            },
        ),
    ]
