# Generated by Django 4.2.9 on 2025-12-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0004_whatsappcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Website URL scraped', max_length=2000)),
                ('final_url', models.URLField(blank=True, help_text='Final URL after redirects', max_length=2000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scraping', 'Scraping'), ('completed', 'Completed'), ('failed', 'Failed'), ('no_content', 'No Content')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if scraping failed', null=True)),
                ('http_status_code', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('emails', models.JSONField(default=list, help_text='List of extracted email addresses')),
                ('emails_count', models.IntegerField(default=0, help_text='Number of emails found')),
                ('page_title', models.CharField(blank=True, help_text='<title> tag content', max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='Meta keywords', null=True)),
                ('headings', models.JSONField(default=dict, help_text='Headings by level: {h1: [...], h2: [...], ...}')),
                ('paragraphs', models.JSONField(default=list, help_text='Main paragraph content (cleaned)')),
                ('navigation_links', models.JSONField(default=list, help_text='Main navigation menu items')),
                ('footer_content', models.TextField(blank=True, help_text='Footer text content', null=True)),
                ('phone_numbers', models.JSONField(default=list, help_text='Phone numbers found on page')),
                ('addresses', models.JSONField(default=list, help_text='Addresses found on page')),
                ('social_links', models.JSONField(default=dict, help_text='Social media links: {facebook: url, ...}')),
                ('full_text', models.TextField(blank=True, help_text='Full page text content (cleaned)', null=True)),
                ('full_text_length', models.IntegerField(default=0, help_text='Character count of full text')),
                ('raw_html', models.TextField(blank=True, help_text='Raw HTML content (compressed)', null=True)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated business summary', null=True)),
                ('ai_services', models.JSONField(default=list, help_text='AI-extracted services/products')),
                ('ai_keywords', models.JSONField(default=list, help_text='AI-extracted business keywords')),
                ('ai_tone', models.CharField(blank=True, help_text='AI-detected business tone (formal, casual, etc.)', max_length=50, null=True)),
                ('ai_processed_at', models.DateTimeField(blank=True, help_text='When AI analysis was done', null=True)),
                ('scraped_at', models.DateTimeField(blank=True, help_text='When the website was scraped', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_data', to='gmaps_leads.gmapslead')),
            ],
            options={
                'verbose_name': 'Lead Website',
                'verbose_name_plural': 'Lead Websites',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='gmaps_leads_status_bf4eae_idx'), models.Index(fields=['emails_count'], name='gmaps_leads_emails__cc878c_idx'), models.Index(fields=['scraped_at'], name='gmaps_leads_scraped_7c44b9_idx')],
            },
        ),
    ]
