# Generated by Django 4.2.9 on 2025-12-09 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmaps_leads', '0005_leadwebsite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Template name/identifier', max_length=255, null=True)),
                ('template_type', models.CharField(choices=[('outreach', 'Cold Outreach'), ('followup', 'Follow-up'), ('introduction', 'Introduction'), ('proposal', 'Business Proposal'), ('custom', 'Custom')], default='outreach', max_length=20)),
                ('subject', models.CharField(help_text='Email subject line', max_length=500)),
                ('body_html', models.TextField(help_text='Email body in HTML format (rich text)')),
                ('body_plain', models.TextField(blank=True, help_text='Plain text version of email body', null=True)),
                ('recipient_email', models.EmailField(blank=True, help_text="Target email (defaults to lead's email)", max_length=254, null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='Recipient name for personalization', max_length=255, null=True)),
                ('sender_name', models.CharField(blank=True, help_text='From name', max_length=255, null=True)),
                ('sender_email', models.EmailField(blank=True, help_text='From email', max_length=254, null=True)),
                ('reply_to', models.EmailField(blank=True, help_text='Reply-to email', max_length=254, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'AI Generating'), ('ready', 'Ready to Send'), ('approved', 'Approved'), ('sent', 'Sent'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Status details/error message', null=True)),
                ('ai_model', models.CharField(blank=True, help_text='AI model used for generation', max_length=100, null=True)),
                ('ai_prompt_used', models.TextField(blank=True, help_text='Prompt used to generate this email', null=True)),
                ('ai_generation_time', models.FloatField(blank=True, help_text='Time taken to generate (seconds)', null=True)),
                ('ai_tokens_used', models.IntegerField(blank=True, help_text='Tokens used in generation', null=True)),
                ('variables', models.JSONField(default=dict, help_text='Variables used in template: {var_name: value}')),
                ('is_personalized', models.BooleanField(default=False, help_text='Whether AI personalized this for the specific lead')),
                ('personalization_score', models.FloatField(blank=True, help_text='AI confidence score 0-1', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When email was sent', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When email was opened (if tracked)', null=True)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='When link was clicked (if tracked)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='gmaps_leads.gmapslead')),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='gmaps_leads_status_bd2115_idx'), models.Index(fields=['template_type'], name='gmaps_leads_templat_d96dd4_idx'), models.Index(fields=['lead', 'status'], name='gmaps_leads_lead_id_01cac5_idx')],
            },
        ),
    ]
