# Generated by Django 4.2.9 on 2025-12-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0006_emailtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='ai_generation_time',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='ai_prompt_used',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='ai_tokens_used',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='is_personalized',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='personalization_score',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='variables',
        ),
    ]
