# Generated by Django 4.2.9 on 2025-12-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0007_remove_emailtemplate_ai_generation_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizedContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Content name/identifier', max_length=255, null=True)),
                ('template_type', models.CharField(choices=[('outreach', 'Cold Outreach'), ('followup', 'Follow-up'), ('introduction', 'Introduction'), ('proposal', 'Business Proposal'), ('custom', 'Custom')], default='outreach', max_length=20)),
                ('subject', models.CharField(help_text='Subject line for the contact content', max_length=500)),
                ('body_html', models.TextField(help_text='Specialized content in HTML format (rich text). CONTACT INFORMATION OF THE SENDER WILL BE ADDED AUTOMATICALLY.')),
                ('body_plain', models.TextField(blank=True, help_text='Plain text version of content (auto-generated, not exposed via API)', null=True)),
                ('recipient_email', models.EmailField(blank=True, help_text="Target email (defaults to lead's email)", max_length=254, null=True)),
                ('recipient_name', models.CharField(blank=True, help_text='Recipient name for personalization', max_length=255, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_contacts', to='gmaps_leads.gmapslead')),
            ],
            options={
                'verbose_name': 'Customized Contact',
                'verbose_name_plural': 'Customized Contacts',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
    ]
