# Generated by Django 4.2.9 on 2025-12-12 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0008_customizedcontact_delete_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customizedcontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
