# Generated by Django 4.2.9 on 2025-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0009_customizedcontact_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customizedcontact',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent', 'Sent')], default='draft', help_text='Status of the contact content', max_length=20),
        ),
    ]
