# Generated by Django 4.2.9 on 2026-01-06 00:00

from django.db import migrations, models


def dedupe_leads(apps, schema_editor):
    """
    Remove duplicate leads per job before enforcing uniqueness.
    
    Keeps the earliest record (lowest ID) for each (job, cid/data_id/link) key.
    """
    Lead = apps.get_model('gmaps_leads', 'GmapsLead')
    
    seen_keys = set()
    duplicate_ids = []
    
    qs = Lead.objects.all().only('id', 'job_id', 'cid', 'data_id', 'link').order_by('id')
    for lead in qs.iterator():
        keys = []
        if lead.cid:
            keys.append(('cid', lead.cid))
        if lead.data_id:
            keys.append(('data_id', lead.data_id))
        if lead.link:
            keys.append(('link', lead.link))
        
        duplicate = False
        for field, value in keys:
            key = (lead.job_id, field, value)
            if key in seen_keys:
                duplicate = True
                break
        
        if duplicate:
            duplicate_ids.append(lead.id)
            continue
        
        for field, value in keys:
            seen_keys.add((lead.job_id, field, value))
    
    if duplicate_ids:
        Lead.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0010_customizedcontact_status'),
    ]

    operations = [
        migrations.RunPython(dedupe_leads, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='gmapslead',
            constraint=models.UniqueConstraint(fields=['job', 'cid'], name='gmapslead_job_cid_unique'),
        ),
        migrations.AddConstraint(
            model_name='gmapslead',
            constraint=models.UniqueConstraint(fields=['job', 'data_id'], name='gmapslead_job_data_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='gmapslead',
            constraint=models.UniqueConstraint(fields=['job', 'link'], name='gmapslead_job_link_unique'),
        ),
    ]
