# Generated by Django 4.2.9 on 2025-12-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0012_chatwootcontactsync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatwootcontactsync',
            options={'ordering': ['-id'], 'verbose_name': 'Customized Contact', 'verbose_name_plural': 'Customized Contacts'},
        ),
        migrations.AlterModelOptions(
            name='customizedcontact',
            options={},
        ),
        migrations.AlterField(
            model_name='chatwootcontactsync',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
