# Generated by Django 4.2.9 on 2025-12-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0013_alter_chatwootcontactsync_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatwootcontactsync',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Chatwoot Contact Sync', 'verbose_name_plural': 'Chatwoot Contact Syncs'},
        ),
    ]
