# Generated by Django 4.2.9 on 2025-12-16 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0014_alter_chatwootcontactsync_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatwootContact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('additional_attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_attributes', models.JSONField(blank=True, default=dict, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('contact_type', models.IntegerField(blank=True, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=50, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('company_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Chatwoot Contact (RO)',
                'verbose_name_plural': 'Chatwoot Contacts (RO)',
                'db_table': 'contacts',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AIMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_type', models.CharField(choices=[('note', 'Note'), ('progress', 'Progress Status')], max_length=20)),
                ('content', models.TextField(help_text='Details of the memory or progress status (e.g., campaign id, done/left counts, notes, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Memory',
                'verbose_name_plural': 'AI Memories',
                'ordering': ['-created_at'],
            },
        ),
    ]
