# Generated by Django 4.2.9 on 2025-12-16 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmaps_leads', '0015_chatwootcontact_aimemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text_template', models.TextField(help_text='Use simple placeholders like {{business_name}}, {{category}}, {{website}}')),
                ('media_url', models.URLField(blank=True, null=True)),
                ('throttle_per_minute', models.IntegerField(default=20, help_text='Max messages per minute')),
                ('delay_min_ms', models.IntegerField(default=10000, help_text='Minimum delay between sends (ms)')),
                ('delay_max_ms', models.IntegerField(default=15000, help_text='Maximum delay between sends (ms)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_campaigns', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_campaigns', to='gmaps_leads.scrapejob')),
            ],
            options={
                'verbose_name': 'WhatsApp Campaign',
                'verbose_name_plural': 'WhatsApp Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_text', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='gmaps_leads.whatsappcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_campaign_recipients', to='gmaps_leads.gmapslead')),
                ('whatsapp_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='gmaps_leads.whatsappcontact')),
            ],
            options={
                'verbose_name': 'WhatsApp Campaign Recipient',
                'verbose_name_plural': 'WhatsApp Campaign Recipients',
                'indexes': [models.Index(fields=['campaign', 'status'], name='gmaps_leads_campaig_bf6887_idx'), models.Index(fields=['lead'], name='gmaps_leads_lead_id_ceca75_idx')],
            },
        ),
    ]
