# Generated by Django 4.2.9 on 2025-12-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0016_whatsappcampaign_whatsappcampaignrecipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplatePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_template_pools', to='gmaps_leads.scrapejob')),
            ],
            options={
                'verbose_name': 'WhatsApp Template Pool',
                'verbose_name_plural': 'WhatsApp Template Pools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Template text. Supports {{business_name}}, {{category}}, {{website}}.')),
                ('media_url', models.URLField(blank=True, null=True)),
                ('weight', models.IntegerField(default=1, help_text='Weight for random selection')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='gmaps_leads.whatsapptemplatepool')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='whatsappcampaign',
            name='template_pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='gmaps_leads.whatsapptemplatepool'),
        ),
        migrations.AddField(
            model_name='whatsappcampaignrecipient',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='gmaps_leads.whatsapptemplate'),
        ),
    ]
