# Generated by Django 4.2.9 on 2025-12-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0017_whatsapptemplatepool_whatsapptemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappcampaign',
            name='text_template',
            field=models.TextField(blank=True, default='', help_text='Fallback template if pool is empty. Supports {{business_name}}, {{category}}, {{website}}.'),
        ),
    ]
