# Generated by Django 4.2.9 on 2025-12-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0018_alter_whatsappcampaign_text_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcampaignrecipient',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
