# Generated by Django 4.2.9 on 2025-12-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmaps_leads', '0019_whatsappcampaignrecipient_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='synced_to_waha',
            field=models.BooleanField(default=False, help_text='Marked after a successful WAHA sync'),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='waha_sync_attempts',
            field=models.IntegerField(default=0, help_text='Number of attempts to sync this contact to WAHA'),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='waha_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time this contact synced to WAHA', null=True),
        ),
    ]
