"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os, random, string, inspect
from pathlib import Path
from dotenv import load_dotenv
from str2bool import str2bool

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'Super_Secr3t_9999')

# Enable/Disable DEBUG Mode
DEBUG = str2bool(os.environ.get('DEBUG'))
#print(' DEBUG -> ' + str(DEBUG) ) 

# IPs allowed to see debug toolbar
INTERNAL_IPS = [
    "127.0.0.1",
]

ALLOWED_HOSTS = ['*']

# Add here your deployment HOSTS
CSRF_TRUSTED_ORIGINS = ['https://app.whatsynaptic.tech', 'http://localhost:8000', 'http://127.0.0.1:8000']

# Allow embedding in iframes (for integration with other sites)
X_FRAME_OPTIONS = "ALLOWALL"

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:    
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "accounts_plus",
    'admin_datta.apps.AdminDattaConfig',  # Re-enabled - module is installed
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Serve UI pages
    "apps.pages",

    # Tooling API-GEN
    'rest_framework',            # Include DRF           # <-- NEW 
    'rest_framework.authtoken',
    'drf_spectacular',           # OpenAPI 3.1 schema generation
    "n8n_mirror",
    
    # Google Maps Leads
    "gmaps_leads",

    # SQL Explorer for database exploration
    "explorer",

    # CORS headers for Pengaa Flow
    "corsheaders",

    # Debug
    "debug_toolbar",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS - must be before CommonMiddleware
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

HOME_TEMPLATES = os.path.join(BASE_DIR, 'templates') 

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [HOME_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DB_ENGINE   = os.getenv('DB_ENGINE'   , None)
DB_USERNAME = os.getenv('DB_USERNAME' , None)
DB_PASS     = os.getenv('DB_PASS'     , None)
DB_HOST     = os.getenv('DB_HOST'     , None)
DB_PORT     = os.getenv('DB_PORT'     , None)
DB_NAME     = os.getenv('DB_NAME'     , None)

N8N_DB_NAME = os.getenv("N8N_DB_NAME")
N8N_DB_USER = os.getenv("N8N_DB_USER")
N8N_DB_PASSWORD = os.getenv("N8N_DB_PASSWORD")
N8N_DB_HOST = os.getenv("N8N_DB_HOST")
N8N_DB_PORT = os.getenv("N8N_DB_PORT")

# Evolution API Database
EVO_DB_NAME = os.getenv("EVO_DB_NAME")
EVO_DB_USER = os.getenv("EVO_DB_USER")
EVO_DB_PASSWORD = os.getenv("EVO_DB_PASSWORD")
EVO_DB_HOST = os.getenv("EVO_DB_HOST")
EVO_DB_PORT = os.getenv("EVO_DB_PORT", "5432")

if DB_ENGINE and DB_NAME and DB_USERNAME:
    DATABASES = { 
      'default': {
        'ENGINE'  : 'django.db.backends.' + DB_ENGINE, 
        'NAME'    : DB_NAME,
        'USER'    : DB_USERNAME,
        'PASSWORD': DB_PASS,
        'HOST'    : DB_HOST,
        'PORT'    : DB_PORT,
        }, 
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'db.sqlite3',
        }
    }

DATABASES["n8n"] = {
    "ENGINE": "django.db.backends.postgresql_psycopg2",
    "NAME": N8N_DB_NAME,
    "USER": N8N_DB_USER,
    "PASSWORD": N8N_DB_PASSWORD,
    "HOST": N8N_DB_HOST,
    "PORT": N8N_DB_PORT,
}

# Evolution API database (for SQL Explorer)
if EVO_DB_NAME and EVO_DB_USER:
    DATABASES["evolution"] = {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": EVO_DB_NAME,
        "USER": EVO_DB_USER,
        "PASSWORD": EVO_DB_PASSWORD,
        "HOST": EVO_DB_HOST,
        "PORT": EVO_DB_PORT,
    }

DATABASE_ROUTERS = ["project_root.db_routers.N8nRouter"]

# Disable migrations for unmanaged n8n mirror models
MIGRATION_MODULES = {"n8n_mirror": None}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

#if not DEBUG:
#    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Session settings - keep users logged in
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists after browser close
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on each request
SESSION_COOKIE_NAME = 'n8n_mirror_sessionid'  # Unique session cookie name
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# DRF Spectacular Settings (OpenAPI 3.1)
SPECTACULAR_SETTINGS = {
    'TITLE': 'GMaps Leads AI Email API',
    'DESCRIPTION': '''
API for AI-driven email outreach based on Google Maps lead data.

## Workflow

1. **AI fetches lead context** via `GET /api/gmaps-leads/{id}/context/`
2. **AI generates personalized email** using the business information
3. **AI posts email template** via `POST /api/gmaps-leads/{id}/email-template/`
4. **Signal emitted** when `mark_ready=true` - template ready for human review
5. **Human reviews** in admin panel and approves/rejects

## Key Endpoints

- `GET /api/gmaps-leads/with-emails/` - Find leads ready for outreach
- `GET /api/gmaps-leads/{id}/context/` - Get comprehensive lead data for AI
- `POST /api/gmaps-leads/{id}/email-template/` - Submit AI-generated email
- `PATCH /api/email-templates/{id}/status/` - Update template status
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/gmaps-leads/api/',
    'TAGS': [
        {'name': 'AI Email Generation', 'description': 'Endpoints for AI to generate personalized emails'},
        {'name': 'Email Templates', 'description': 'Manage email templates'},
        {'name': 'Jobs', 'description': 'Scrape job management'},
        {'name': 'Leads', 'description': 'Lead management'},
    ],
}

# SQL Explorer Configuration
EXPLORER_CONNECTIONS = {'default': 'default', 'n8n': 'n8n'}
EXPLORER_DEFAULT_CONNECTION = 'n8n'

# Add Evolution API to explorer if configured
if EVO_DB_NAME and EVO_DB_USER:
    EXPLORER_CONNECTIONS['evolution'] = 'evolution'
    EXPLORER_DEFAULT_CONNECTION = 'evolution'

# Security: Only allow SELECT queries
EXPLORER_SQL_BLACKLIST = ('ALTER', 'CREATE', 'DELETE', 'DROP', 'INSERT', 'RENAME', 'TRUNCATE', 'UPDATE')

# Only staff users can access SQL Explorer
EXPLORER_PERMISSION_VIEW = lambda r: r.user.is_staff
EXPLORER_PERMISSION_CHANGE = lambda r: r.user.is_staff

# SQL Assistant powered by OpenAI
EXPLORER_AI_API_KEY = os.getenv('OPENAI_API_KEY', '')
EXPLORER_ASSISTANT_MODEL = {
    "name": "gpt-4o",
    "max_tokens": 4096,
}

########################################
# CORS Settings for Pengaa Flow
########################################
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://localhost:8420",
    "http://127.0.0.1:8420",
]
CORS_ALLOW_CREDENTIALS = True  # Allow cookies/session auth

########################################
# Google Maps Scraper API Settings
########################################
GMAPS_SCRAPER_API_URL = os.getenv('GMAPS_SCRAPER_API_URL', 'http://localhost:8080')
GMAPS_CSV_DOWNLOAD_DIR = os.path.join(BASE_DIR, 'gmaps_downloads')  # Directory for downloaded CSV files
