"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os, random, string, inspect, json
from pathlib import Path
from dotenv import load_dotenv
from str2bool import str2bool

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'Super_Secr3t_9999')

# Enable/Disable DEBUG Mode
DEBUG = str2bool(os.environ.get('DEBUG'))
#print(' DEBUG -> ' + str(DEBUG) ) 

# IPs allowed to see debug toolbar
INTERNAL_IPS = [
    "127.0.0.1",
]

ALLOWED_HOSTS = ['*']

# Add here your deployment HOSTS
CSRF_TRUSTED_ORIGINS = ['https://app.whatsynaptic.tech', 'http://localhost:8000', 'http://127.0.0.1:8000','https://app.delilclinic.com']

# Allow embedding in iframes (for integration with other sites)
X_FRAME_OPTIONS = "ALLOWALL"

# WAHA WhatsApp API
WAHA_SERVICE_FQDN = os.getenv("SERVICE_FQDN_WAHA")
WAHA_SERVICE_URL = os.getenv("SERVICE_URL_WAHA")
WAHA_API_KEY = os.getenv("WAHA_API_KEY") or os.getenv("API_KEY")
WAHA_SESSION = os.getenv("WAHA_SESSION") or os.getenv("session") or "default"
WAHA_CONTACTS_PATH = os.getenv("WAHA_CONTACTS_PATH")
WAHA_TIMEOUT = int(os.getenv("WAHA_TIMEOUT", "15"))

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:    
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "accounts_plus",
    'admin_datta.apps.AdminDattaConfig',  # Re-enabled - module is installed
    "core_dashboard",
    "ckeditor",
    "import_export",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Serve UI pages
    "apps.pages",

    # Tooling API-GEN
    'rest_framework',            # Include DRF           # <-- NEW 
    'rest_framework.authtoken',
    'drf_spectacular',           # OpenAPI 3.1 schema generation
    "n8n_mirror",
    
    # Google Maps Leads
    "gmaps_leads",

    # Email infrastructure
    "anymail",
    "apps.emailing",

    # SQL Explorer for database exploration
    "explorer",

    # CORS headers for Pengaa Flow
    "corsheaders",

    # Debug
    "debug_toolbar",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS - must be before CommonMiddleware
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

HOME_TEMPLATES = os.path.join(BASE_DIR, 'templates') 

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [HOME_TEMPLATES],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DB_ENGINE   = os.getenv('DB_ENGINE'   , None)
DB_USERNAME = os.getenv('DB_USERNAME' , None)
DB_PASS     = os.getenv('DB_PASS'     , None)
DB_HOST     = os.getenv('DB_HOST'     , None)
DB_PORT     = os.getenv('DB_PORT'     , None)
DB_NAME     = os.getenv('DB_NAME'     , None)

N8N_DB_NAME = os.getenv("N8N_DB_NAME")
N8N_DB_USER = os.getenv("N8N_DB_USER")
N8N_DB_PASSWORD = os.getenv("N8N_DB_PASSWORD")
N8N_DB_HOST = os.getenv("N8N_DB_HOST")
N8N_DB_PORT = os.getenv("N8N_DB_PORT")

# Evolution API Database
EVO_DB_NAME = os.getenv("EVO_DB_NAME")
EVO_DB_USER = os.getenv("EVO_DB_USER")
EVO_DB_PASSWORD = os.getenv("EVO_DB_PASSWORD")
EVO_DB_HOST = os.getenv("EVO_DB_HOST")
EVO_DB_PORT = os.getenv("EVO_DB_PORT", "5432")

# Chatwoot DB (read-only mirror)
CHATWOOT_DB_NAME = os.getenv("CHATWOOT_DB_NAME")
CHATWOOT_DB_USER = os.getenv("CHATWOOT_DB_USER")
CHATWOOT_DB_PASSWORD = os.getenv("CHATWOOT_DB_PASSWORD")
CHATWOOT_DB_HOST = os.getenv("CHATWOOT_DB_HOST")
CHATWOOT_DB_PORT = os.getenv("CHATWOOT_DB_PORT", "5432")

if DB_ENGINE and DB_NAME and DB_USERNAME:
    DATABASES = { 
      'default': {
        'ENGINE'  : 'django.db.backends.' + DB_ENGINE, 
        'NAME'    : DB_NAME,
        'USER'    : DB_USERNAME,
        'PASSWORD': DB_PASS,
        'HOST'    : DB_HOST,
        'PORT'    : DB_PORT,
        }, 
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': 'db.sqlite3',
        }
    }

DATABASES["n8n"] = {
    "ENGINE": "django.db.backends.postgresql_psycopg2",
    "NAME": N8N_DB_NAME,
    "USER": N8N_DB_USER,
    "PASSWORD": N8N_DB_PASSWORD,
    "HOST": N8N_DB_HOST,
    "PORT": N8N_DB_PORT,
}

# Evolution API database (for SQL Explorer)
if EVO_DB_NAME and EVO_DB_USER:
    DATABASES["evolution"] = {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": EVO_DB_NAME,
        "USER": EVO_DB_USER,
        "PASSWORD": EVO_DB_PASSWORD,
        "HOST": EVO_DB_HOST,
        "PORT": EVO_DB_PORT,
    }

# Chatwoot read-only DB (optional)
if CHATWOOT_DB_NAME and CHATWOOT_DB_USER:
    DATABASES["chatwoot"] = {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": CHATWOOT_DB_NAME,
        "USER": CHATWOOT_DB_USER,
        "PASSWORD": CHATWOOT_DB_PASSWORD,
        "HOST": CHATWOOT_DB_HOST,
        "PORT": CHATWOOT_DB_PORT,
    }

DATABASE_ROUTERS = ["project_root.db_routers.N8nRouter"]

# Disable migrations for unmanaged n8n mirror models
MIGRATION_MODULES = {"n8n_mirror": None}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

#if not DEBUG:
#    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

# Session settings - keep users logged in
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # Session persists after browser close
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on each request
SESSION_COOKIE_NAME = 'n8n_mirror_sessionid'  # Unique session cookie name
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'

REST_FRAMEWORK = {
    # Keep the API open for external callers (no auth or permission enforcement)
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# DRF Spectacular Settings (OpenAPI 3.1)
SPECTACULAR_SETTINGS = {
    'TITLE': 'GMaps Leads AI Email API',
    'DESCRIPTION': '''
API for AI-driven email outreach based on Google Maps lead data.

## Workflow

1. **AI fetches lead context** via `GET /api/gmaps-leads/{id}/context/`
2. **AI generates personalized email** using the business information
3. **AI posts email template** via `POST /api/gmaps-leads/{id}/email-template/`
4. **Signal emitted** when `mark_ready=true` - template ready for human review
5. **Human reviews** in admin panel and approves/rejects

## Key Endpoints

- `GET /api/gmaps-leads/with-emails/` - Find leads ready for outreach
- `GET /api/gmaps-leads/{id}/context/` - Get comprehensive lead data for AI
- `POST /api/gmaps-leads/{id}/email-template/` - Submit AI-generated email
- `PATCH /api/email-templates/{id}/status/` - Update template status
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': r'/gmaps-leads/api/',
    'SERVERS': [
        {'url': 'https://app.whatsynaptic.tech', 'description': 'Production'},
    ],
    # No auth requirements in the generated schema (keep endpoints open)
    'SECURITY': [],
    'OPENAPI_VERSION': '3.1.0',
    'TAGS': [
        {'name': 'AI Email Generation', 'description': 'Endpoints for AI to generate personalized emails'},
        {'name': 'Email Templates', 'description': 'Manage email templates'},
        {'name': 'Jobs', 'description': 'Scrape job management'},
        {'name': 'Leads', 'description': 'Lead management'},
    ],
}

# SQL Explorer Configuration
EXPLORER_CONNECTIONS = {'default': 'default', 'n8n': 'n8n'}
EXPLORER_DEFAULT_CONNECTION = 'n8n'

# Add Evolution API to explorer if configured
if EVO_DB_NAME and EVO_DB_USER:
    EXPLORER_CONNECTIONS['evolution'] = 'evolution'
    EXPLORER_DEFAULT_CONNECTION = 'evolution'

# Security: Only allow SELECT queries
EXPLORER_SQL_BLACKLIST = ('ALTER', 'CREATE', 'DELETE', 'DROP', 'INSERT', 'RENAME', 'TRUNCATE', 'UPDATE')

# Only staff users can access SQL Explorer
EXPLORER_PERMISSION_VIEW = lambda r: r.user.is_staff
EXPLORER_PERMISSION_CHANGE = lambda r: r.user.is_staff

# SQL Assistant powered by OpenAI
EXPLORER_AI_API_KEY = os.getenv('OPENAI_API_KEY', '')
EXPLORER_ASSISTANT_MODEL = {
    "name": "gpt-4o",
    "max_tokens": 4096,
}

########################################
# CORS Settings for Pengaa Flow
########################################
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://localhost:8420",
    "http://127.0.0.1:8420",
]
CORS_ALLOW_CREDENTIALS = True  # Allow cookies/session auth

########################################
# Google Maps Scraper API Settings
########################################
GMAPS_SCRAPER_API_URL = os.getenv('GMAPS_SCRAPER_API_URL', 'http://localhost:8080')
GMAPS_CSV_DOWNLOAD_DIR = os.path.join(BASE_DIR, 'gmaps_downloads')  # Directory for downloaded CSV files


########################################
# Email delivery (SMTP/ESP via Anymail)
########################################
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", os.getenv("EMAIL_HOST_USER", "no-reply@example.com"))
EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "smtp_primary")

EMAIL_PROVIDERS = {
    "smtp_primary": {
        "BACKEND": os.getenv("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"),
        "HOST": os.getenv("EMAIL_HOST", "localhost"),
        "PORT": int(os.getenv("EMAIL_PORT", "587")),
        "USERNAME": os.getenv("EMAIL_HOST_USER", ""),
        "PASSWORD": os.getenv("EMAIL_HOST_PASSWORD", ""),
        "USE_TLS": str2bool(os.getenv("EMAIL_USE_TLS", "True")),
        "USE_SSL": str2bool(os.getenv("EMAIL_USE_SSL", "False")),
        "FROM_EMAIL": DEFAULT_FROM_EMAIL,
    }
}

if os.getenv("SECONDARY_EMAIL_HOST"):
    EMAIL_PROVIDERS["smtp_secondary"] = {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
        "HOST": os.getenv("SECONDARY_EMAIL_HOST"),
        "PORT": int(os.getenv("SECONDARY_EMAIL_PORT", "587")),
        "USERNAME": os.getenv("SECONDARY_EMAIL_USER", ""),
        "PASSWORD": os.getenv("SECONDARY_EMAIL_PASSWORD", ""),
        "USE_TLS": str2bool(os.getenv("SECONDARY_EMAIL_USE_TLS", "True")),
        "USE_SSL": str2bool(os.getenv("SECONDARY_EMAIL_USE_SSL", "False")),
        "FROM_EMAIL": os.getenv("SECONDARY_DEFAULT_FROM_EMAIL", DEFAULT_FROM_EMAIL),
    }

providers_json = os.getenv("EMAIL_PROVIDERS_JSON")
if providers_json:
    try:
        EMAIL_PROVIDERS.update(json.loads(providers_json))
    except Exception:
        # Invalid JSON is ignored to avoid breaking settings load
        pass

# Optional ESP configuration via django-anymail
ANYMAIL = {
    "SEND_DEFAULTS": {"metadata": {"app": "core"}},
}
anymail_provider = os.getenv("ANYMAIL_PROVIDER")
anymail_api_key = os.getenv("ANYMAIL_API_KEY")
if anymail_provider and anymail_api_key:
    provider_key = anymail_provider.lower()
    ANYMAIL[f"{provider_key.upper()}_API_KEY"] = anymail_api_key
    api_url = os.getenv("ANYMAIL_API_URL")
    if api_url:
        ANYMAIL[f"{provider_key.upper()}_API_URL"] = api_url
    EMAIL_PROVIDERS[f"esp_{provider_key}"] = {
        "BACKEND": f"anymail.backends.{provider_key}.EmailBackend",
        "FROM_EMAIL": DEFAULT_FROM_EMAIL,
    }

active_provider = EMAIL_PROVIDERS.get(EMAIL_PROVIDER, EMAIL_PROVIDERS.get("smtp_primary", {}))
EMAIL_BACKEND = active_provider.get("BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = active_provider.get("HOST", os.getenv("EMAIL_HOST", "localhost"))
EMAIL_PORT = active_provider.get("PORT", int(os.getenv("EMAIL_PORT", "587")))
EMAIL_USE_TLS = active_provider.get("USE_TLS", str2bool(os.getenv("EMAIL_USE_TLS", "True")))
EMAIL_USE_SSL = active_provider.get("USE_SSL", str2bool(os.getenv("EMAIL_USE_SSL", "False")))
EMAIL_HOST_USER = active_provider.get("USERNAME", os.getenv("EMAIL_HOST_USER", ""))
EMAIL_HOST_PASSWORD = active_provider.get("PASSWORD", os.getenv("EMAIL_HOST_PASSWORD", ""))

########################################
# Chatwoot (optional, for threading replies)
########################################
CHATWOOT_ENABLED = str2bool(os.getenv("CHATWOOT_ENABLED", "False"))
CHATWOOT_BASE_URL = os.getenv("CHATWOOT_BASE_URL", "").rstrip("/")
CHATWOOT_ACCOUNT_ID = os.getenv("CHATWOOT_ACCOUNT_ID")
CHATWOOT_INBOX_ID = os.getenv("CHATWOOT_INBOX_ID")
CHATWOOT_API_TOKEN = os.getenv("CHATWOOT_API_TOKEN")
CHATWOOT_API_PATH = os.getenv("CHATWOOT_API_PATH", "/api/v1")



JAZZMIN_SETTINGS = {
    "show_ui_builder": True,
    "navigation_expanded": False,
    "custom_css": "css/jazzmin-custom.css",
    "icons": {
        # App-level defaults
        "gmaps_leads": "si-icon icon-gmaps",
        "accounts_plus": "si-icon icon-accounts",
        "emailing": "si-icon icon-gmail",
        "pages": "si-icon icon-pages",
        "admin": "si-icon icon-settings",
        "explorer": "si-icon icon-explorer",
        "n8n_mirror": "si-icon icon-n8n",
        "auth": "si-icon icon-accounts",
        "authtoken": "si-icon icon-accounts",

        # Model-level overrides
        "gmaps_leads.scrapejob": "si-icon icon-gmaps",
        "gmaps_leads.gmapslead": "si-icon icon-gmaps",
        "gmaps_leads.whatsappcontact": "si-icon icon-whatsapp",
        "gmaps_leads.chatwootcontactsync": "si-icon icon-chatwoot",
        "gmaps_leads.chatwootcontact": "si-icon icon-chatwoot",
        "gmaps_leads.leadwebsite": "si-icon icon-gmaps",
        "gmaps_leads.customizedcontact": "si-icon icon-email",
        # n8n mirror model names (lowercase, no underscores)
        "n8n_mirror.credentialsentity": "si-icon icon-n8n",
        "n8n_mirror.executionentity": "si-icon icon-n8n",
        "n8n_mirror.executiondata": "si-icon icon-n8n",
        "n8n_mirror.executionannotations": "si-icon icon-n8n",
        "n8n_mirror.executionmetadata": "si-icon icon-n8n",
        "n8n_mirror.sharedworkflow": "si-icon icon-n8n",
        "n8n_mirror.tagentity": "si-icon icon-n8n",
        "n8n_mirror.userapikeys": "si-icon icon-n8n",
        "n8n_mirror.userentity": "si-icon icon-n8n",
        "n8n_mirror.webhookentity": "si-icon icon-n8n",
        "n8n_mirror.workflowentity": "si-icon icon-n8n",
        "n8n_mirror.project": "si-icon icon-n8n",
        "n8n_mirror.projectrelation": "si-icon icon-n8n",
        "n8n_mirror.sharedcredentials": "si-icon icon-n8n",
        # pages models
        "pages.userwhatsappinstance": "si-icon icon-whatsapp",
        "pages.usertelegramcredential": "si-icon icon-telegram",
        "pages.product": "si-icon icon-pages",
        "pages.n8nexecutionsnapshot": "si-icon icon-n8n",
        # emailing models
        "emailing.emailtemplate": "si-icon icon-gmail",
        "emailing.emailcampaign": "si-icon icon-gmail",
        "emailing.emailsend": "si-icon icon-gmail",
        "emailing.recipient": "si-icon icon-gmail",
        "emailing.emailaddress": "si-icon icon-gmail",
        "emailing.campaignrecipient": "si-icon icon-gmail",
        # explorer
        "explorer.query": "si-icon icon-explorer",
        "explorer.databaseconnection": "si-icon icon-explorer",
        "explorer.querylog": "si-icon icon-explorer",
        "explorer.queryfavorite": "si-icon icon-explorer",
        "explorer.explorervalue": "si-icon icon-explorer",
        "explorer.tabledescription": "si-icon icon-explorer",
        "explorer.promptlog": "si-icon icon-explorer",
        # accounts_plus
        "accounts_plus.openaikeypool": "si-icon icon-accounts",
        "accounts_plus.usern8nprofile": "si-icon icon-accounts",
        # authtoken
        "authtoken.token": "si-icon icon-accounts",
        "authtoken.tokenproxy": "si-icon icon-accounts",
        "auth.user": "si-icon icon-accounts",
        "auth.Group": "si-icon icon-accounts",
        'site_brand': 'Whatsynaptic',
        'site_header': 'Whatsynaptic',
    },
    "default_icon_parents": "si-icon icon-default",
    "default_icon_children": "si-icon icon-default",
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "lightblue",
    "navbar": "navbar-dark navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-lime",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "cyborg",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}
