# Generated by Django 4.2.9 on 2025-11-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_userwhatsappinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwhatsappinstance',
            name='hash_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userwhatsappinstance',
            name='instance_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userwhatsappinstance',
            name='status',
            field=models.CharField(choices=[('connecting', 'Connecting'), ('connected', 'Connected'), ('disconnected', 'Disconnected')], default='connecting', max_length=20),
        ),
    ]
