# Generated by Django 4.2.9 on 2025-12-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_n8nexecutionsnapshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='n8nexecutionsnapshot',
            new_name='pages_n8nex_workflo_77736a_idx',
            old_name='pages_n8nex_workflo_7f3978_idx',
        ),
        migrations.RenameIndex(
            model_name='n8nexecutionsnapshot',
            new_name='pages_n8nex_user_id_c6c73e_idx',
            old_name='pages_n8nex_user_id_9e4045_idx',
        ),
        migrations.AlterField(
            model_name='n8nexecutionsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
